enabled: true
logo_url: ''
phone_number: +128-658-5876(248-order)
location:
  - 'Via Romagnola'
  - '524 - Roma Italy'
newsletter: ''
social_links:
  facebook: '#'
  twitter: '#'
  gplus: '#'
  pinterest: '#'
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      paths:
        - user/themes/machine
